# Compile options
VERBOSE=n
OPT=g
USE_NANO=n
SEMIHOST=n
USE_FPU=y

# Libraries
USE_LPCOPEN=y
USE_SAPI=y
USE_FREERTOS=y
FREERTOS_HEAP_TYPE=4
LOAD_INRAM=n

#EXTRA INCLUDE PATHS
INCLUDES += -I$(PROGRAM_PATH_AND_NAME)/common/inc
INCLUDES += -I$(PROGRAM_PATH_AND_NAME)/educiaa/inc

#EXTRA SOURCE FILES
SRC += $(wildcard $(PROGRAM_PATH_AND_NAME)/common/src/*.c)




